# Generated by Django 5.2.4 on 2025-12-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_pdf_file_remove_course_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. A-Level Math 66', max_length=200)),
                ('category', models.CharField(help_text='The Label. e.g. Math, Physics, PAT1', max_length=100)),
                ('pdf_file', models.FileField(upload_to='past_papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
