# Generated by Django 5.2.4 on 2025-12-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_instructor_alter_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_file',
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='youtube_url',
            field=models.URLField(default='', help_text='Enter YouTube URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Enter the full YouTube URL (e.g. https://www.youtube.com/watch?v=...)', null=True),
        ),
    ]
